# Generated by Django 5.0.3 on 2024-04-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
